# Generated by Django 6.0.6 on 2026-06-16 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detector_name', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_flags', to='invoices.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='IdleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('root_cause', models.CharField(choices=[('awaiting_parts', 'Awaiting Parts'), ('awaiting_paperwork', 'Awaiting Paperwork'), ('no_driver', 'No Driver Assigned'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idle_events', to='vehicles.vehicle')),
            ],
        ),
    ]
