# Generated by Django 6.0.6 on 2026-06-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_add_is_demo'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('organization', 'vin')},
        ),
    ]
